[workspace]
members = [
    "crates/relayrl_framework",
    "crates/relayrl_python",
    "crates/relayrl_cli",
    "crates/relayrl_types",
    "crates/relayrl_algorithms",
]
resolver = "2"

[workspace.dependencies]
relayrl_framework = { version = "0.5.0-alpha.1", path = "crates/relayrl_framework"}
relayrl_types = { version = "0.4.1", path = "crates/relayrl_types"}
relayrl_algorithms = { version = "0.1.0", path = "crates/relayrl_algorithms"}

burn-tensor = "0.20.0"
burn-ndarray = "0.20.0"
burn-tch = "0.20.0"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = true
