[package]
name = "relayrl_algorithms"
version = "0.1.0"
edition = "2024"

[dependencies]
# tch = { version = "0.18.1", features = ["download-libtorch", "python-extension"] }
# burn = "0.18.0"
# burn-ndarray = "0.18.0"
